server:
  port: 8080

#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: upload
#          uri: 'http://localhost:8081/'
#          predicates:
#            - Path=/service/**
#        - id: download
#          uri: 'http://localhost:8082/'
#          predicates:
#            - Path=/service/**
#        - id: delete
#          uri: 'http://localhost:8083/ '
#          predicates:
#            - Path=/service/**

#  main:
#    web-application-type: reactive

